#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH=$HOME/.go

export EDITOR="mvim -v"
export VISUAL="mvim -v"

PATH=/usr/local/heroku/bin:$PATH
PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
PATH=$HOME/.rvm/bin:$PATH
PATH=/usr/local/bin:$PATH
PATH=$PATH:$HOME/bin
PATH=$PATH:/usr/local/share/npm/bin
PATH=$PATH:$HOME/.cask/bin
PATH=$PATH:$GOPATH/bin

hash dnvm.sh &> /dev/null
if [ "$?" -eq "0" ]; then
  source dnvm.sh
fi

alias pt='pt --smart-case'
alias ag='ag --smart-case'
alias npmls='npm ls -g --depth=0'
alias ls='ls --color'
